version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install asciidoctor
  build:
    commands:
      - asciidoctor -b html *.adoc -D deploy/
      - cp *.png deploy/
      - cp *.jpg deploy/
      - cp *.pdf deploy/
      - cp -r qualify/ deploy/qualify/
  post_build:
    commands:
      - aws s3 sync deploy/ s3://skillsheet-bucket --delete
