version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install asciidoctor
  build:
    commands:
      - asciidoctor -b html skillsheet.adoc -D deploy/
      - cp develop_actual*.png deploy/
  post_build:
    commands:
      - aws s3 sync deploy/ s3://skillsheet-bucket --delete
